transforms:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: target/dev.duckdb
      schema: main
      extensions:
        - ducklake
      attach:
        - path: ducklake:/Users/adammarples/projects/testbed/src_db/metadata.ducklake
          alias: metadata
