dbt_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../../data/host.duckdb
      database: lake
      schema: analytics
      extensions:
        - httpfs
        - ducklake
      attach:
        - path: ducklake:../../data/lakehouse.ducklake
          alias: lake
          options:
            data_path: s3://ducklake-data/data/
      settings:
        s3_endpoint: localhost:9000
        s3_use_ssl: false
        s3_url_style: path
        s3_access_key_id: minioadmin
        s3_secret_access_key: minioadmin
