dbt_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ducklake:../../data/lake.ducklake
      schema: analytics
      extensions:
        - ducklake
      settings:
        s3_endpoint: localhost:9000
        s3_use_ssl: false
        s3_url_style: path
        s3_access_key_id: minioadmin
        s3_secret_access_key: minioadmin
