dbt_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../../dst_db/analytics.duckdb
      schema: main
      extensions:
        - ducklake
      attach:
        - path: ducklake:../../src_db/metadata.ducklake
          alias: metadata
